% Solve a Clustering Problem with a Self-Organizing Map
% Script generated by Neural Clustering app
% Created 13-May-2024 17:02:49
%
% This script assumes these variables are defined:
%
%   iris - input data.

x = iris';

% Create a Self-Organizing Map
dimension1 = 40;
dimension2 = 40;
net = selforgmap([dimension1 dimension2]);

% Train the Network
[net,tr] = train(net,x);

% Test the Network
y = net(x);

% View the Network
view(net)

% Plots
% Uncomment these lines to enable various plots.
figure, plotsomtop(net)
figure, plotsomnc(net)
figure, plotsomnd(net)
figure, plotsomplanes(net)
figure, plotsomhits(net,x)
figure, plotsompos(net,x)

